# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SMGP_dowloaderDialog
                                 A QGIS plugin
 This plugin alows you to download Polish geological maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-24
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Karol Majewski/PIG-PIB
        email                : majewskikar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'SMGP_dowloader_dialog_base.ui'))


class SMGP_dowloaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SMGP_dowloaderDialog, self).__init__(parent)
        self.setupUi(self)
